title: "Customer Pages"
description: "Digital customer pages"

baseurl: ""
url: "https://power-internet-solutions.github.io"

collections:
  customers:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "customers"
    values:
      layout: "customer"
